language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="214f09db-9231-4b50-8215-8acc6e2f1839"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -integer.args@gmail.com
    on_success: never # default: change
    on_failure: always # default: always